using Faaz.Services.Consultant.Domain.Entities;
using Faaz.Services.Consultant.Infrastructure.Interfaces;
using Faaz.Services.Consultant.WebHost.Features.ConsultantApplication.DTOs;
using Faaz.SharedKernel.Abstractions;
using Faaz.SharedKernel.Exceptions;
using MediatR;
using Microsoft.Extensions.Logging;
using static Faaz.Services.Consultant.Domain.ConsultantEnums;
using static Faaz.SharedKernel.SharedEnums;

namespace Faaz.Services.Consultant.WebHost.Features.ConsultantApplication.Commands;

public class InitialiseApplicationCommand : IRequest<Guid>
{
    public InitialiseApplicationDto PostModel { get; set; } = null!;
}

internal sealed class InitialiseApplicationCommandHandler : IRequestHandler<InitialiseApplicationCommand, Guid>
{
    private static readonly HashSet<string> AllowedMimeTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "application/pdf",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "image/png",
        "image/jpeg",
        "image/gif"
    };

    private const long MaxFileSizeBytes = 10 * 1024 * 1024; // 10 MB

    private readonly IConsultantApplicationServices _appServices;
    private readonly Faaz.SharedKernel.Abstractions.IFileStorageService _fileStorage;
    private readonly ILogger<InitialiseApplicationCommandHandler> _logger;

    public InitialiseApplicationCommandHandler(
        IConsultantApplicationServices appServices,
        Faaz.SharedKernel.Abstractions.IFileStorageService fileStorage,
        ILogger<InitialiseApplicationCommandHandler> logger)
    {
        _appServices = appServices;
        _fileStorage = fileStorage;
        _logger = logger;
    }

    public async Task<Guid> Handle(InitialiseApplicationCommand command, CancellationToken ct)
    {
        var dto = command.PostModel;

        if (await _appServices.GetByEmailAsync(dto.Email, ct) is not null)
            throw new ConflictException(
                "An application with this email address already exists, contact support.");

        if (await _appServices.GetByPhoneNumberAsync(dto.PhoneNumber, ct) is not null)
            throw new ConflictException(
                "An application with this phone number already exists, contact support.");

        // Build the application entity — Id is set in the constructor (RT.Comb) so we
        // know it before hitting the DB. Files are saved to disk using that Id as the folder.
        // SrNo is generated by DB IDENTITY on insert.
        var application = new Domain.Entities.ConsultantApplication
        {
            Email                = dto.Email,
            FirstName            = dto.FirstName,
            LastName             = dto.LastName,
            PhoneNumber          = dto.PhoneNumber,
            IsUkBased            = dto.IsUkBased,
            CurrentRole          = dto.CurrentRole,
            ExpertiseArea        = dto.ExpertiseArea,
            YearsOfExperience    = dto.YearsOfExperience,
            DateOfBirth          = dto.DateOfBirth,
            Nationality          = dto.Nationality,
            CountryOfResidence   = dto.CountryOfResidence,
            LinkedInProfileUrl   = dto.LinkedInProfileUrl,
            HighestQualification = dto.HighestQualification,
            PrimaryLanguage      = dto.PrimaryLanguage,
            PersonalStatement    = dto.PersonalStatement,
            ConsultationMode     = dto.ConsultationMode,
            SubmittedAt          = DateTime.UtcNow
        };

        // Save files to disk BEFORE AddAsync. Adding documents to the collection here
        // means EF Core sees the complete graph when AddAsync is called and saves
        // application + documents in a single SaveChangesAsync call.
        if (dto.Files is { Count: > 0 })
            await AttachDocumentsAsync(application, dto, ct);

        // One AddAsync + one SaveChangesAsync — complete graph saved together
        await _appServices.AddAsync(application, ct);
        await _appServices.SaveChangesAsync(ct);

        _logger.LogInformation(
            "Consultant application initialised. ApplicationId: {ApplicationId}, Documents: {DocCount}",
            application.Id, application.Documents.Count);

        return application.Id;
    }

    private async Task AttachDocumentsAsync(
        Domain.Entities.ConsultantApplication application,
        InitialiseApplicationDto dto,
        CancellationToken ct)
    {
        for (int i = 0; i < dto.Files!.Count; i++)
        {
            var file = dto.Files[i];

            if (file.Length > MaxFileSizeBytes)
            {
                _logger.LogWarning("Skipping {FileName}: exceeds 10 MB limit", file.FileName);
                continue;
            }

            if (!AllowedMimeTypes.Contains(file.ContentType))
            {
                _logger.LogWarning("Skipping {FileName}: unsupported content type {ContentType}", file.FileName, file.ContentType);
                continue;
            }

            var docType = dto.DocumentTypes != null && dto.DocumentTypes.Count > i && dto.DocumentTypes[i].HasValue
                ? dto.DocumentTypes[i]!.Value
                : ApplicationDocumentType.OtherSupportingDocument;

            var relativePath = await _fileStorage.UploadAsync(
                file.OpenReadStream(), file.FileName, FileCategory.Applications, ct);

            // Add directly to the collection before EF Core tracking begins
            application.Documents.Add(new ConsultantApplicationDocument
            {
                ApplicationId = application.Id,
                DocumentType  = docType,
                FileName      = file.FileName,
                FilePath      = relativePath,
                ContentType   = file.ContentType,
                FileSizeBytes = file.Length,
                UploadedAt    = DateTime.UtcNow
            });
        }
    }
}
