// <auto-generated />
using System;
using Faaz.Services.Consultant.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faaz.Services.Consultant.Infrastructure.Migrations
{
    [DbContext(typeof(ConsultantDbContext))]
    partial class ConsultantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("consultant")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1021);

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int")
                        .HasColumnOrder(1019);

                    b.Property<int?>("ConsultationMode")
                        .HasColumnType("int")
                        .HasColumnOrder(1017);

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1007);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1009);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnOrder(1005);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnOrder(1001);

                    b.Property<string>("ExpertiseArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1011);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<int?>("HighestQualification")
                        .HasColumnType("int")
                        .HasColumnOrder(1013);

                    b.Property<string>("HighestQualificationOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1026);

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1010);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<bool>("IsUkBased")
                        .HasColumnType("bit")
                        .HasColumnOrder(1008);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<string>("LinkedInProfileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1015);

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1006);

                    b.Property<string>("PersonalStatement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1016);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1014);

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1018);

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1022);

                    b.Property<DateTime?>("SetupInviteSentAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1025);

                    b.Property<string>("SetupInviteToken")
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)")
                        .HasColumnOrder(1023);

                    b.Property<DateTime?>("SetupInviteTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1024);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1020);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnOrder(1012);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStatus")
                        .HasDatabaseName("IX_ConsultantApplications_ApplicationStatus");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_ConsultantApplications_Email");

                    b.HasIndex("SetupInviteToken")
                        .HasDatabaseName("IX_ConsultantApplications_SetupInviteToken")
                        .HasFilter("[SetupInviteToken] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConsultantApplications_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ConsultantApplications", "consultant");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnOrder(1001);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1005);

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1006);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_ConsultantApplicationDocuments_ApplicationId");

                    b.ToTable("ConsultantApplicationDocuments", "consultant");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantAvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConsultantProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnOrder(1005);

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnOrder(1002);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<TimeOnly?>("EndTimeLocal")
                        .HasColumnType("time")
                        .HasColumnOrder(1004);

                    b.Property<bool>("IsBlockedDate")
                        .HasColumnType("bit")
                        .HasColumnOrder(1001);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1006);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<TimeOnly?>("StartTimeLocal")
                        .HasColumnType("time")
                        .HasColumnOrder(1003);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("ConsultantProfileId")
                        .HasDatabaseName("IX_ConsultantAvailabilitySlots_ConsultantProfileId");

                    b.ToTable("ConsultantAvailabilitySlots", "consultant");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConsultantProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1004);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1005);

                    b.HasKey("Id");

                    b.HasIndex("ConsultantProfileId")
                        .HasDatabaseName("IX_ConsultantCredentials_ConsultantProfileId");

                    b.ToTable("ConsultantCredentials", "consultant");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1001);

                    b.Property<int>("CallPreference")
                        .HasColumnType("int")
                        .HasColumnOrder(1015);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1005);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<string>("FullLegalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1006);

                    b.Property<string>("IntroVideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1014);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(1020);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1021);

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit")
                        .HasColumnOrder(1019);

                    b.Property<bool>("IsStripeChargesEnabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(1024);

                    b.Property<bool>("IsStripeDetailsSubmitted")
                        .HasColumnType("bit")
                        .HasColumnOrder(1023);

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1007);

                    b.Property<int>("MaxAdvanceBookingDays")
                        .HasColumnType("int")
                        .HasColumnOrder(1017);

                    b.Property<int>("MinBookingNoticeHours")
                        .HasColumnType("int")
                        .HasColumnOrder(1016);

                    b.Property<string>("ProfessionalPhotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.PrimitiveCollection<string>("ServicesOffered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1012);

                    b.PrimitiveCollection<string>("SpecialisedUniversities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1011);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1022);

                    b.PrimitiveCollection<string>("StudyLevelsOffered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1009);

                    b.PrimitiveCollection<string>("SubjectAreas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1010);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1018);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<string>("WrittenBio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1013);

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnOrder(1008);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConsultantProfiles_ApplicationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConsultantProfiles_UserId");

                    b.HasIndex("IsActive", "IsProfileComplete")
                        .HasDatabaseName("IX_ConsultantProfiles_IsActive_IsProfileComplete");

                    b.ToTable("ConsultantProfiles", "consultant");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantSessionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConsultantProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnOrder(1003);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(1006);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<decimal>("PriceGbp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1004);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnOrder(1005);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("ConsultantProfileId")
                        .HasDatabaseName("IX_ConsultantSessionTypes_ConsultantProfileId");

                    b.ToTable("ConsultantSessionTypes", "consultant");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantApplicationDocument", b =>
                {
                    b.HasOne("Faaz.Services.Consultant.Domain.Entities.ConsultantApplication", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantAvailabilitySlot", b =>
                {
                    b.HasOne("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", "Profile")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("ConsultantProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantCredential", b =>
                {
                    b.HasOne("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", "Profile")
                        .WithMany("Credentials")
                        .HasForeignKey("ConsultantProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultantCredentials_ConsultantProfiles_ConsultantProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", b =>
                {
                    b.HasOne("Faaz.Services.Consultant.Domain.Entities.ConsultantApplication", "Application")
                        .WithOne("Profile")
                        .HasForeignKey("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultantProfiles_ConsultantApplications_ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantSessionType", b =>
                {
                    b.HasOne("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", "Profile")
                        .WithMany("SessionTypes")
                        .HasForeignKey("ConsultantProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantApplication", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Faaz.Services.Consultant.Domain.Entities.ConsultantProfile", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Credentials");

                    b.Navigation("SessionTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
