// <auto-generated />
using System;
using Faaz.Services.Payment.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faaz.Services.Payment.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1003);

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<decimal>("ConsultantPayout")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1005);

                    b.Property<Guid>("ConsultantUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1002);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1007);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1006);

                    b.Property<string>("FailureMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1013);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1014);

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1004);

                    b.Property<string>("PromoCodeUsed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1008);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(1009);

                    b.Property<string>("StripeChargeId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1011);

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1012);

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(1010);

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SrNo")
                        .IsUnique();

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique();

                    b.ToTable("Payments", "payment");
                });

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1002);

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<Guid>("ConsultantUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1009);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1006);

                    b.Property<DateTime?>("ScheduledReleaseAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1005);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(1004);

                    b.Property<string>("StripeConnectAccountId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1007);

                    b.Property<string>("StripeTransferId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1008);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ConsultantUserId");

                    b.HasIndex("SrNo")
                        .IsUnique();

                    b.ToTable("Payouts", "payment");
                });

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1000);

                    b.Property<Guid?>("ConsultantProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int")
                        .HasColumnOrder(1005);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1010);

                    b.Property<int>("DiscountType")
                        .HasColumnType("int")
                        .HasColumnOrder(1001);

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1002);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(1008);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1003);

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int")
                        .HasColumnOrder(1004);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1006);

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1007);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SrNo")
                        .IsUnique();

                    b.ToTable("PromoCodes", "payment");
                });

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnOrder(1003);

                    b.Property<Guid?>("AppealId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1009);

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1011);

                    b.Property<bool>("IsAppealRefund")
                        .HasColumnType("bit")
                        .HasColumnOrder(1008);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1006);

                    b.Property<int>("RefundPercentage")
                        .HasColumnType("int")
                        .HasColumnOrder(1007);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(1005);

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(1010);

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1002);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SrNo")
                        .IsUnique();

                    b.HasIndex("StripeRefundId");

                    b.ToTable("Refunds", "payment");
                });

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.StripeWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1006);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1005);

                    b.Property<bool>("Processed")
                        .HasColumnType("bit")
                        .HasColumnOrder(1003);

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1004);

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1002);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("StripeEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(1000);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique();

                    b.ToTable("StripeWebhookEvents", "payment");
                });

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.Refund", b =>
                {
                    b.HasOne("Faaz.Services.Payment.Domain.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Faaz.Services.Payment.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
