// <auto-generated />
using System;
using Faaz.Services.Student.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faaz.Services.Student.Infrastructure.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("student")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.PostgraduateData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<string>("PostgraduateStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.Property<string>("ResearchInterests")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1005);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<string>("UndergraduateDegree")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<string>("UndergraduateGrade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<string>("UndergraduateUniversity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentPostgraduateData_StudentProfileId");

                    b.ToTable("StudentPostgraduateData", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.SavedConsultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConsultantUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId", "ConsultantUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_SavedConsultants_Student_Consultant");

                    b.ToTable("SavedConsultants", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.SixthFormData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("ExamBoard")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<string>("PredictedGrades")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.PrimitiveCollection<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<int?>("TargetEntryYear")
                        .HasColumnType("int")
                        .HasColumnOrder(1005);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentSixthFormData_StudentProfileId");

                    b.ToTable("StudentSixthFormData", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.PrimitiveCollection<string>("AdditionalLanguages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1009);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1013);

                    b.Property<string>("CountryOfCitizenship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1005);

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1006);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnOrder(1004);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1007);

                    b.Property<string>("FirstLanguage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1008);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<bool>("IsOnboardingComplete")
                        .HasColumnType("bit")
                        .HasColumnOrder(1015);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1003);

                    b.Property<int>("ProfileCompleteness")
                        .HasColumnType("int")
                        .HasColumnOrder(1014);

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1012);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int?>("StudyTrack")
                        .HasColumnType("int")
                        .HasColumnOrder(1010);

                    b.Property<int?>("TargetStudyLevel")
                        .HasColumnType("int")
                        .HasColumnOrder(1011);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentProfiles_UserId");

                    b.ToTable("StudentProfiles", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileHelpService", b =>
                {
                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentProfileId", "ServiceId");

                    b.ToTable("StudentProfileHelpServices", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileTargetProgramme", b =>
                {
                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentProfileId", "ProgrammeId");

                    b.ToTable("StudentProfileTargetProgrammes", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileTargetSubject", b =>
                {
                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentProfileId", "SubjectId");

                    b.ToTable("StudentProfileTargetSubjects", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileTargetUniversity", b =>
                {
                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentProfileId", "UniversityId");

                    b.ToTable("StudentProfileTargetUniversities", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.UndergraduateData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9000);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9002);

                    b.Property<string>("CurrentGrade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1004);

                    b.Property<string>("CurrentUniversity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1001);

                    b.Property<string>("DegreeSubject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1002);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9006);

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9005);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9004);

                    b.Property<bool>("IsGapYear")
                        .HasColumnType("bit")
                        .HasColumnOrder(1005);

                    b.Property<int>("SrNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1000);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9001);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9003);

                    b.Property<int?>("YearOfStudy")
                        .HasColumnType("int")
                        .HasColumnOrder(1003);

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentUndergraduateData_StudentProfileId");

                    b.ToTable("StudentUndergraduateData", "student");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.PostgraduateData", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithOne("PostgraduateData")
                        .HasForeignKey("Faaz.Services.Student.Domain.Entities.PostgraduateData", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.SixthFormData", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithOne("SixthFormData")
                        .HasForeignKey("Faaz.Services.Student.Domain.Entities.SixthFormData", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileHelpService", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("HelpServices")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileTargetProgramme", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("TargetProgrammes")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileTargetSubject", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("TargetSubjects")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfileTargetUniversity", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("TargetUniversities")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.UndergraduateData", b =>
                {
                    b.HasOne("Faaz.Services.Student.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithOne("UndergraduateData")
                        .HasForeignKey("Faaz.Services.Student.Domain.Entities.UndergraduateData", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Faaz.Services.Student.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("HelpServices");

                    b.Navigation("PostgraduateData");

                    b.Navigation("SixthFormData");

                    b.Navigation("TargetProgrammes");

                    b.Navigation("TargetSubjects");

                    b.Navigation("TargetUniversities");

                    b.Navigation("UndergraduateData");
                });
#pragma warning restore 612, 618
        }
    }
}
