namespace Faaz.SharedKernel.Entities;

public abstract class BaseEntity : Trackable
{
    public Guid Id { get; protected set; }
    // DB IDENTITY — value generated by the database on insert, no application assignment needed.
    public int SrNo { get; set; }
    public bool IsDeleted { get; set; } = false;
}
