using Faaz.Services.Consultant.Infrastructure.Interfaces;
using Faaz.SharedKernel.Exceptions;
using MediatR;
using Microsoft.Extensions.Logging;

namespace Faaz.Services.Consultant.WebHost.Features.ConsultantProfile.Commands;

public class CreateProfileStubCommand : IRequest
{
    public required Guid UserId { get; init; }
}

internal sealed class CreateProfileStubCommandHandler : IRequestHandler<CreateProfileStubCommand>
{
    private readonly IConsultantProfileServices _profileServices;
    private readonly IConsultantApplicationServices _applicationServices;
    private readonly ILogger<CreateProfileStubCommandHandler> _logger;

    public CreateProfileStubCommandHandler(
        IConsultantProfileServices profileServices,
        IConsultantApplicationServices applicationServices,
        ILogger<CreateProfileStubCommandHandler> logger)
    {
        _profileServices = profileServices;
        _applicationServices = applicationServices;
        _logger = logger;
    }

    public async Task Handle(CreateProfileStubCommand command, CancellationToken ct)
    {
        if (await _profileServices.ExistsForUserAsync(command.UserId, ct))
            return;

        var application = await _applicationServices.GetByUserIdAsync(command.UserId, ct)
            ?? throw new NotFoundException("ConsultantApplication", command.UserId);

        // SrNo generated by DB IDENTITY on insert.
        // Pre-fill from the EoI so the consultant doesn't re-enter data they already provided.
        var profile = new Domain.Entities.ConsultantProfile
        {
            UserId            = command.UserId,
            ApplicationId     = application.Id,
            FullLegalName     = $"{application.FirstName} {application.LastName}".Trim(),
            DisplayName       = application.FirstName,
            CurrentRole       = application.CurrentRole,
            LinkedInUrl       = application.LinkedInProfileUrl,
            YearsOfExperience = application.YearsOfExperience
        };

        await _profileServices.AddAsync(profile, ct);
        await _profileServices.SaveChangesAsync(ct);

        _logger.LogInformation("Consultant profile stub created. UserId: {UserId}", command.UserId);
    }
}
