using Faaz.Services.Consultant.Domain.Entities;
using Faaz.Services.Consultant.Infrastructure.Interfaces;
using Faaz.Services.Consultant.WebHost.Features.ConsultantProfile.DTOs;
using Faaz.SharedKernel.Exceptions;
using MediatR;

namespace Faaz.Services.Consultant.WebHost.Features.ConsultantProfile.Commands;

public class UpdatePricingCommand : IRequest
{
    public Guid UserId { get; set; }
    public UpdatePricingDto PutModel { get; set; } = null!;
}

internal sealed class UpdatePricingCommandHandler : IRequestHandler<UpdatePricingCommand>
{
    private readonly IConsultantProfileServices _profileServices;

    public UpdatePricingCommandHandler(IConsultantProfileServices profileServices)
    {
        _profileServices = profileServices;
    }

    public async Task Handle(UpdatePricingCommand command, CancellationToken ct)
    {
        var profile = await _profileServices.GetByUserIdWithCollectionsAsync(command.UserId, ct)
            ?? throw new NotFoundException("ConsultantProfile", command.UserId);

        var incoming   = command.PutModel.SessionTypes;
        var incomingIds = incoming.Where(d => d.Id.HasValue).Select(d => d.Id!.Value).ToHashSet();

        // Hard-delete any existing session type not present in the incoming list.
        var toDelete = profile.SessionTypes.Where(s => !incomingIds.Contains(s.Id)).ToList();
        foreach (var s in toDelete)
            profile.SessionTypes.Remove(s);

        foreach (var dto in incoming)
        {
            if (dto.Id.HasValue)
            {
                // Update existing — only if it belongs to this profile (IDOR guard).
                var existing = profile.SessionTypes.FirstOrDefault(s => s.Id == dto.Id.Value)
                    ?? throw new NotFoundException("ConsultantSessionType", dto.Id.Value);

                existing.Name            = dto.Name;
                existing.DurationMinutes = dto.DurationMinutes;
                existing.PriceGbp        = dto.PriceGbp;
                existing.Description     = dto.Description;
                existing.IsActive        = dto.IsActive;
                existing.SortOrder       = dto.SortOrder;
            }
            else
            {
                // No id supplied → create new; SrNo generated by DB IDENTITY.
                await _profileServices.AddSessionTypeAsync(new ConsultantSessionType
                {
                    ConsultantProfileId = profile.Id,
                    Name                = dto.Name,
                    DurationMinutes     = dto.DurationMinutes,
                    PriceGbp            = dto.PriceGbp,
                    Description         = dto.Description,
                    IsActive            = dto.IsActive,
                    SortOrder           = dto.SortOrder
                }, ct);
            }
        }

        await _profileServices.TryAutoActivateAsync(profile, ct);
        await _profileServices.SaveChangesAsync(ct);
    }
}
