using Faaz.Services.Consultant.Domain.Entities;
using Faaz.Services.Consultant.Infrastructure.Interfaces;
using Faaz.Services.Consultant.WebHost.Features.ConsultantProfile.DTOs;
using Faaz.SharedKernel.Exceptions;
using MediatR;

namespace Faaz.Services.Consultant.WebHost.Features.ConsultantProfile.Commands;

public class UpdateAvailabilityCommand : IRequest
{
    public Guid UserId { get; set; }
    public UpdateAvailabilityDto PutModel { get; set; } = null!;
}

internal sealed class UpdateAvailabilityCommandHandler : IRequestHandler<UpdateAvailabilityCommand>
{
    private readonly IConsultantProfileServices _profileServices;

    public UpdateAvailabilityCommandHandler(IConsultantProfileServices profileServices)
    {
        _profileServices = profileServices;
    }

    public async Task Handle(UpdateAvailabilityCommand command, CancellationToken ct)
    {
        var profile = await _profileServices.GetByUserIdWithCollectionsAsync(command.UserId, ct)
            ?? throw new NotFoundException("ConsultantProfile", command.UserId);

        // Soft-delete all existing entries (both weekly slots and blocked dates).
        // Never use collection.Clear() — it generates hard DELETEs which fail with the
        // soft-delete global query filter in play.
        foreach (var existing in profile.AvailabilitySlots)
            existing.IsDeleted = true;

        // New records — SrNo generated by DB IDENTITY.
        foreach (var slot in command.PutModel.WeeklySlots)
        {
            await _profileServices.AddAvailabilitySlotAsync(new ConsultantAvailabilitySlot
            {
                ConsultantProfileId = profile.Id,
                IsBlockedDate       = false,
                DayOfWeek           = (DayOfWeek)slot.DayOfWeek,
                StartTimeUtc        = slot.StartTime,
                EndTimeUtc          = slot.EndTime
            }, ct);
        }

        foreach (var blocked in command.PutModel.BlockedDates)
        {
            await _profileServices.AddAvailabilitySlotAsync(new ConsultantAvailabilitySlot
            {
                ConsultantProfileId = profile.Id,
                IsBlockedDate       = true,
                Date                = blocked.Date,
                Reason              = blocked.Reason
            }, ct);
        }

        await _profileServices.TryAutoActivateAsync(profile, ct);
        await _profileServices.SaveChangesAsync(ct);
    }
}
