using Faaz.Services.Student.Infrastructure.Interfaces;
using StudentProfileEntity = Faaz.Services.Student.Domain.Entities.StudentProfile;
using Faaz.Services.Student.WebHost.Features.StudentProfile.DTOs;
using MediatR;
using Microsoft.Extensions.Logging;

namespace Faaz.Services.Student.WebHost.Features.StudentProfile.Commands;

public class CreateProfileStubCommand : IRequest
{
    public CreateProfileStubDto PostModel { get; set; } = null!;
}

internal sealed class CreateProfileStubCommandHandler : IRequestHandler<CreateProfileStubCommand>
{
    private readonly IStudentProfileServices _profileServices;
    private readonly ILogger<CreateProfileStubCommandHandler> _logger;

    public CreateProfileStubCommandHandler(IStudentProfileServices profileServices, ILogger<CreateProfileStubCommandHandler> logger)
    {
        _profileServices = profileServices;
        _logger = logger;
    }

    public async Task Handle(CreateProfileStubCommand command, CancellationToken ct)
    {
        if (await _profileServices.ExistsForUserAsync(command.PostModel.UserId, ct))
            return;

        // SrNo generated by DB IDENTITY on insert.
        var profile = new StudentProfileEntity
        {
            UserId    = command.PostModel.UserId,
            Email     = command.PostModel.Email,
            FirstName = command.PostModel.FirstName,
            LastName  = command.PostModel.LastName
        };

        await _profileServices.AddAsync(profile, ct);
        await _profileServices.SaveChangesAsync(ct);

        _logger.LogInformation("Student profile stub created for UserId: {UserId}", command.PostModel.UserId);
    }
}
