using Faaz.Services.Identity.Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using static Faaz.Services.Identity.Domain.IdentityEnums;

namespace Faaz.Services.Identity.WebHost.Seeding;

public static class AdminSeeder
{
    public static async Task SeedAsync(IServiceProvider services, ILogger logger)
    {
        var userManager = services.GetRequiredService<UserManager<ApplicationUser>>();
        var config      = services.GetRequiredService<IConfiguration>();

        var email    = config["AdminSeed:Email"] ?? "admin@faaz.co.uk";
        var password = config["AdminSeed:Password"];

        if (string.IsNullOrWhiteSpace(password))
        {
            logger.LogWarning("AdminSeed:Password not configured — admin user skipped");
            return;
        }

        if (await userManager.FindByEmailAsync(email) is not null)
        {
            logger.LogDebug("Admin user {Email} already exists — skipping seed", email);
            return;
        }

        // SrNo generated by DB IDENTITY on insert.
        var admin = new ApplicationUser
        {
            UserName           = email,
            Email              = email,
            NormalizedEmail    = email.ToUpperInvariant(),
            NormalizedUserName = email.ToUpperInvariant(),
            FirstName          = "Platform",
            LastName           = "Admin",
            Role               = UserRole.Admin,
            Status             = UserStatus.Active,
            IsEmailVerified    = true,
            EmailConfirmed     = true,
            SecurityStamp      = Guid.NewGuid().ToString("D"),
            ConcurrencyStamp   = Guid.NewGuid().ToString("D"),
            CreatedAt          = DateTime.UtcNow
        };

        var result = await userManager.CreateAsync(admin, password);
        if (!result.Succeeded)
        {
            var errors = string.Join(", ", result.Errors.Select(e => e.Description));
            logger.LogError("Admin user seed failed: {Errors}", errors);
            return;
        }

        var roleResult = await userManager.AddToRoleAsync(admin, nameof(UserRole.Admin));
        if (!roleResult.Succeeded)
        {
            var errors = string.Join(", ", roleResult.Errors.Select(e => e.Description));
            logger.LogError("Admin role assignment failed: {Errors}", errors);
            return;
        }

        logger.LogInformation("Admin user seeded: {Email}", email);
    }
}
